In [1]:
import numpy as np

# Exercises!

In your numpy-pandas-visualization-exercises repo, create a file named `numpy_exercises.py` for this exercise.

Use the following code for the questions below:

In [79]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [3]:
#print(a < 0)

#I'm not really sure what's happening when I do the below. Is this changing the array, or only listing the values where the condition is true?
len(a[a < 0])

4

### 2. How many positive numbers are there?

In [75]:
#print(a > 0)

#len(a[a > 0])

#len() has it's limitations, so I will need to be mindful of that in the future. Therefore:

a_positive = a[a > 0]

a_positive.size
#copy this same format to the later cells to get rid of the len() based solutions. 
#The size tool will return the number of elements in the array *REGARDLESS OF NESTING*. Len will not do that if there are nested lists, as it will only go one layer deep.

10

### 3. How many even positive numbers are there?

In [5]:
#Why does this work with parentheses, but not without?

len(a[(a > 0) & (a % 2 == 0)])

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [77]:
len(a[(a + 3) > 0])

#Adam's solution (he recommends doing it in multiple steps for the sake of clarity)
add_three = a + 3
#The below will not actually *change* the add_three variable, because there are no assignment variables here, so I will need to write the whole thing out before adding '.size'
add_three[add_three > 0]

add_three[add_three > 0].size

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [7]:
a_square = a ** 2

print(a_square.std())
print(a_square.mean())

144.0243035046516
74.0


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See [this link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering.

In [80]:
centered = a - a.mean()

centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7. Calculate the z-score for each data point. 

In [9]:
#I wanted to try writing a function for this, to see if it would be possible. In real world work, it may save time and effort to define a function that can calculate this on arrays, rather than typing it out each time. 
# I asked Ryan whether it would be possible to creaete a method for arrays and be able to call something like array.z() in order to have this run automatically. He didn't know off the top of his head how to do that, so I need to do some digging.

def z(array):
    return ((array - array.mean())/array.std())

In [10]:
#I'm testing the formula that I wrote, and it does indeed work.

z(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [81]:
z_score = (a - a.mean())/a.std()

z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8. Copy the setup and exercise directions from [More Numpy Practice](https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your `numpy_exercises.py` and add your solutions.

# Use python's built in functionality/operators to determine the following:

In [ ]:
# I need to go through and redo all of these with the regular Python functionality, as opposed to using numpy right off the bat.

## Setup:

In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


#I need to convert the above list to a NumPy array before I can use any of the array methods built into NumPy
a = np.array(a)

###  Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [16]:
sum_of_a = a.sum()

sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [18]:
min_of_a = a.min()

min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [19]:
max_of_a = a.max()

max_of_a

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [20]:
mean_of_a = a.mean()

mean_of_a

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [23]:
product_of_a = a.prod()

product_of_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [31]:
print(a)

squares_of_a = np.square(a)
squares_of_a

[ 1  2  3  4  5  6  7  8  9 10]


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [34]:
odds_in_a = a[a % 2 != 0]

odds_in_a

array([1, 3, 5, 7, 9])

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [35]:
evens_in_a = a[a % 2 == 0]

evens_in_a

array([ 2,  4,  6,  8, 10])

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [37]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#The above is a list of lists, so I need to convert it to an array before I can do the exercises. 
b = np.array(b)

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [38]:
b.sum()

33

### Exercise 2 - refactor the following to use numpy. 

In [ ]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [39]:
b.min()

3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [ ]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [40]:
b.max()

8

### Exercise 4 - refactor the following using numpy to find the mean of b

In [ ]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [41]:
b.mean()

5.5

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [ ]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [42]:
b.prod()

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [46]:
squares_of_b = np.square(b)

squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

### Exercise 7 - refactor using numpy to determine the odds_in_b

In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [48]:
odds_in_b = b[b % 2 != 0]

odds_in_b

array([3, 5, 7])

### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [49]:
evens_in_b = b[b % 2 == 0]

evens_in_b

array([4, 6, 8])

### Exercise 9 - print out the shape of the array b.

In [51]:
#Why does this not require parentheses in the same way that other methods do?

b.shape

(2, 3)

### Exercise 10 - transpose the array b.

In [84]:
b.transpose()

#OR 

b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [85]:
b.reshape(1, 6)

#OR

b.flatten()

array([3, 4, 5, 6, 7, 8])

## Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [55]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [57]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)

### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

### Exercise 1 - Find the min, max, sum, and product of c.

In [59]:
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


### Exercise 2 - Determine the standard deviation of c.

In [60]:
c.std()

2.581988897471611

### Exercise 3 - Determine the variance of c.

In [61]:
c.var()

6.666666666666667

### Exercise 4 - Print out the shape of the array c

In [63]:
#Again, this one does not require parentheses like the other methods do. 
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.

In [64]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Exercise 6 - Get the dot product of the array c with c.

In [68]:
c.dot(c)
#OR (many of the others can be rewritten like this, too)
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [87]:
#I need to rethink these. I can do the tranposed * the sum

print((c.transpose()) * c.sum())

#Adam's solution:
c * c.T
(c * c.T).sum()

[[ 45 180 315]
 [ 90 225 360]
 [135 270 405]]


261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [88]:
print((c.transpose() * c.prod()))

#Adam's solution:
(c * c.T).prod()

[[ 362880 1451520 2540160]
 [ 725760 1814400 2903040]
 [1088640 2177280 3265920]]


131681894400

## Setup 4

In [89]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

### Exercise 1 - Find the sine of all the numbers in d

In [92]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d

In [93]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d

In [94]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d

In [95]:
d[d < 0]

array([-90, -30, -45, -45])

### Exercise 5 - Find all the positive numbers in d

In [96]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - Return an array of only the unique numbers in d.

In [97]:


#Adam's solution:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.

In [98]:
np.unique(d).size

11

### Exercise 8 - Print out the shape of d.

In [99]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.

In [100]:
d.T.shape

(6, 3)

### Exercise 10 - Reshape d into an array of 9 x 2

In [101]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

**Awesome Bonus** For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type `git clone git@github.com:rougier/numpy-100.git` - Now do `cd numpy-100` on your terminal. - Type `git remote remove origin`, so you won't accidentally try to push your work to Rougier's repo.

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

Go to https://github.com/new to make a new repo. Name it numpy-100.
DO NOT check any check boxes. We need a blank, empty repo.
Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

Now do work, add it, commit it, and push it!